version: '2'

# Define the services/containers to be run
services:

  database: # name of the service
    container_name: "database"
    image: mongo # specify image to build container from
    command: mongod --smallfiles --logpath=/dev/null 

  phones: #name of your service
    build:
      context: ./phones
      dockerfile: test.Dockerfile
    links:
      - database # link this service to the database service
    volumes:
      - ./phones:/usr/src/phones
    environment:
      - DEBUG=1
      - PORT=3001
      - ENV=development
    depends_on:
      - database

  orders: #name of your service
    build:
      context: ./orders
      dockerfile: test.Dockerfile
    links:
      - database # link this service to the database service
      - phones
    volumes:
      - ./orders:/usr/src/orders
    environment:
      - DEBUG=1
      - PORT=3002
      - ENV=development
    depends_on:
      - database
      - phones